#' Add multiple groupings simulataneously
#'
#' Add columns that bin rows into groups. Either use ``pax_add_groupings()`` to
#' add any possible groupings, or individual ``pax_add_*`` functions to add a given group.
#'
#' @param tbl A dplyr query to apply grouping operations to
#' @param groupings List of groupings generated by ``pax_def_groupings()``, will apply each grouping operation in turn
#' @param ignore_missing_col Boolean, should we ignore grouping columns that aren't present in the data?
#' @return \subsection{pax_add_groupings}{A dplyr query, with all grouping columns added}
pax_add_groupings <- function(
  tbl,
  groupings = pax_def_groupings(),
  ignore_missing_col = TRUE
) {
  tbl <- tbl |>
    pax_add_regions(
      groupings$regions,
      ignore_missing_col = ignore_missing_col
    ) |>
    pax_add_gear_group(
      groupings$gear_group,
      ignore_missing_col = ignore_missing_col
    ) |>
    pax_add_lgroups(
      groupings$lgroups,
      ignore_missing_col = ignore_missing_col
    ) |>
    pax_add_temporal_grouping(
      groupings$tgroup,
      ignore_missing_col = ignore_missing_col
    ) |>
    pax_add_yearly_grouping(
      groupings$ygroup,
      ignore_missing_col = ignore_missing_col
    )
  # NB: ocean_depth holds the depth breaks; it used to be passed as
  #     ocean_depth_tbl, so tables with an ocean_depth column (logbooks) failed
  if (!is.null(groupings$ocean_depth)) {
    tbl <- pax_add_ocean_depth_class(
      tbl,
      breaks = groupings$ocean_depth,
      ignore_missing_col = ignore_missing_col
    )
  }
  tbl
}

#' @return \subsection{pax_def_groupings}{List of grouping parameters to hand to ``pax_add_groupings()``}
#' @rdname pax_add_groupings
pax_def_groupings <- function(
  lgroups = seq(0, 200, 5),
  regions = list(all = 101:115),
  tgroup = NULL,
  ygroup = NULL,
  gear_group = NULL,
  ocean_depth = NULL
) {
  list(
    lgroups = lgroups,
    regions = regions,
    tgroup = tgroup,
    ygroup = ygroup,
    gear_group = gear_group,
    ocean_depth = ocean_depth
  )
}

#' @param lgroups Vector of cut-off points. Values define lower bounds, everything above the final bound is considered part of the plus group
#' @return \subsection{pax_add_lgroups}{Query with an additional ``lgroup`` column, binning a ``length`` column}
#' @rdname pax_add_groupings
# Was: tidypax::add_lgroups
pax_add_lgroups <- function(
  tbl,
  lgroups,
  ignore_missing_col = FALSE
) {
  pcon <- dbplyr::remote_con(tbl)

  if (isTRUE(ignore_missing_col) && !("length" %in% colnames(tbl))) {
    # Column not present in this table, do nothing
    return(tbl)
  }

  if (FALSE && all(diff(lgroups) == diff(lgroups)[[1]])) {
    # TODO: Disabled until #11 sorted
    # Even length-groups, we can use modulo arithmetic
    lgroup_min <- min(lgroups)
    lgroup_max <- max(lgroups)
    lgroup_dl <- diff(lgroups)[[1]]

    tbl <- tbl |>
      dplyr::mutate(
        lgroup = least(
          greatest(
            (length - local(lgroup_min)) -
              ((length - local(lgroup_min)) %% local(lgroup_dl)),
            local(lgroup_min)
          ) +
            local(lgroup_min),
          local(lgroup_max)
        )
      )
  } else {
    # Use list_filter to pick off first item to meet condition
    tbl <- tbl |>
      dplyr::mutate(
        # TODO: tidypax::add_lgroups' behaviour was including the lower bound in the previous group,
        #       use < instead of <= here to emulate this, but seems broken.
        #       https://github.com/Hafro/pax/issues/11
        lgroup = dplyr::sql(paste0(
          "list_last(list_filter([",
          paste(as.numeric(lgroups), collapse = ", "),
          "], lambda x : x < length))"
        ))
      )
  }
  return(tbl)
}

#' @param regions List of region name to a vector of divisions, divisions are groups of gridcells described by \var{division_tbl}. Vectors can be ``pax_add_other()`` ("Other" value for gridcells without a matching division/region)
#' @param division_tbl Mapping of gridcell -> division, by default the internal [gridcell] mapping
#' @return \subsection{pax_add_regions}{Query with an additional ``region`` column, binning a ``gridcell`` column}
#' @rdname pax_add_groupings
# Was: tidypax::add_regions
pax_add_regions <- function(
  tbl,
  regions = list(all = 101:115),
  division_tbl = pax_temptbl(dbplyr::remote_con(tbl), "paxdat_gridcell"),
  ignore_missing_col = FALSE
) {
  pcon <- dbplyr::remote_con(tbl)
  tbl_colnames <- colnames(tbl)

  # NSE variables
  gridcell <- NULL
  division <- NULL
  subdivision <- NULL
  region <- NULL

  if (
    isTRUE(ignore_missing_col) &&
      !any(c("gridcell", "division") %in% tbl_colnames)
  ) {
    # Column not present in this table, do nothing
    return(tbl)
  }

  if (is.null(regions)) {
    # No regions given, do nothing
    return(tbl)
  }

  # Pick off any default group
  default_group <- regions[sapply(regions, length) == 0]
  regions <- regions[sapply(regions, length) > 0]
  if (length(default_group) > 1) {
    stop(
      "More than one default region is not allowed, got: ",
      dput(default_group)
    )
  }

  regions_tbl <- data.frame(
    # Repeat the region name from the regions list, one per entry
    region = rep(names(regions), sapply(regions, length)),
    division = unlist(regions)
  )

  out <- tbl
  if (!("division" %in% tbl_colnames)) {
    out <- dplyr::left_join(
      out,
      division_tbl |>
        dplyr::select(gridcell, division, subdivision),
      by = c("gridcell"),
      suffix = c("", ".gridcell")
    )
  }
  out <- dplyr::left_join(
    out,
    pax_temptbl(pcon, regions_tbl),
    by = c("division")
  )

  # Set default for any still-unassigned groups
  if (length(default_group) > 0) {
    out <- dplyr::mutate(
      out,
      region = coalesce(region, local(names(default_group)[[1]]))
    )
  }

  return(out)
}
data_update_gridcell <- function(mar) {
  if (!requireNamespace("mar", quietly = TRUE)) {
    stop("mar package not available, cannot import from DB")
  }

  # NSE variables
  gridcell <- NULL
  division <- NULL
  subdivision <- NULL
  lat <- NULL
  lon <- NULL
  id <- NULL

  mar::tbl_mar(mar, 'ops$bthe."reitmapping"') |>
    dplyr::filter(
      !is.na(gridcell),
      !is.na(division),
      !is.na(subdivision),
      !is.na(lat),
      !is.na(lon)
    ) |>
    dplyr::select(-id) |>
    utils::write.table(file = "pax/data/gridcell.txt")
}

#' @param ocean_depth_tbl Table containing a mapping from ``h3_cells`` to ``ocean_depth``, used when the ``ocean_depth`` column is ``NA``: the mean depth around the record's own ``h3_cells``, see ``fill_resolution``. Records without a position (or outside the table) stay ``NA``, class ``"Unknown"``
#' @param fill_resolution H3 resolution at which the record's cells are matched to ``ocean_depth_tbl`` when filling missing depths (default 6, cells of about 36 km²; the bathymetry is too sparse for the database resolution). Cells without bathymetry at that resolution are matched at the two coarser resolutions
#' @param ocean_depth,breaks Ocean depth breaks, everything beyond the final group is part of a plus group
#' @return \subsection{pax_add_ocean_depth_class}{Query with an additional ``ocean_depth_class`` column, binning a ``ocean_depth`` or ``h3_cells`` column}
#' @rdname pax_add_groupings
# Was: tidypax::add_depth_labels
pax_add_ocean_depth_class <- function(
  tbl,
  ocean_depth_tbl = dplyr::tbl(dbplyr::remote_con(tbl), "ocean_depth"),
  breaks = c(0, 100, 200, 300),
  ignore_missing_col = FALSE,
  fill_resolution = 6
) {
  pcon <- dbplyr::remote_con(tbl)

  # NSE variables
  h3_parent <- NULL
  ocean_depth_class <- NULL
  ocean_depth <- NULL
  ocean_depth_fill <- NULL
  od_depth <- NULL
  od_h3_cells <- NULL
  h3_cell <- NULL
  h3_cells <- NULL

  if (isTRUE(ignore_missing_col) && !("ocean_depth" %in% colnames(tbl))) {
    # Column not present in this table, do nothing
    return(tbl)
  }

  breaks <- sort(breaks)
  b_max <- max(breaks)
  b_labs <- paste(breaks[-length(breaks)], breaks[-1], sep = '-')
  b_labs_plusgroup <- sprintf("%d+", b_max)

  if ("h3_cells" %in% colnames(tbl)) {
    # If depth missing, use the mean depth from ocean_depth_tbl around the
    # record's own h3 cells. NB: This used to be a subquery
    # "WHERE h3_cell IN h3_cells", where h3_cells bound to ocean_depth_tbl's
    # own column, so every missing depth got the mean of the whole table
    # Cells are matched at fill_resolution: the bathymetry has about one
    # point per few cells of the database resolution. Cells without
    # bathymetry at that resolution are tried at the two coarser ones
    for (res in as.integer(fill_resolution) - 0:2) {
      to_parent <- dplyr::sql(paste0(
        "h3_cell_to_parent(h3_cell::UBIGINT, ",
        res,
        ")"
      ))
      od_cells <- ocean_depth_tbl |>
        dplyr::select(od_h3_cells = h3_cells, od_depth = ocean_depth) |>
        dplyr::mutate(h3_cell = dplyr::sql("UNNEST(od_h3_cells)")) |>
        dplyr::mutate(h3_parent = to_parent) |>
        dplyr::select(h3_parent, od_depth)
      depth_fill <- tbl |>
        dplyr::filter(is.na(ocean_depth), !is.na(h3_cells)) |>
        dplyr::distinct(h3_cells) |>
        dplyr::mutate(h3_cell = dplyr::sql("UNNEST(h3_cells)")) |>
        dplyr::mutate(h3_parent = to_parent) |>
        dplyr::inner_join(od_cells, by = "h3_parent") |>
        dplyr::group_by(h3_cells) |>
        # NB: Negative depths are land, a coastal cell is at least 0 m
        dplyr::summarise(
          ocean_depth_fill = pmax(mean(od_depth, na.rm = TRUE), 0, na.rm = TRUE)
        ) |>
        dplyr::ungroup()
      tbl <- tbl |>
        dplyr::left_join(depth_fill, by = "h3_cells") |>
        dplyr::mutate(ocean_depth = coalesce(ocean_depth, ocean_depth_fill)) |>
        dplyr::select(-ocean_depth_fill)
    }
  }

  tbl |>
    dplyr::mutate(
      ocean_depth_class = case_when(
        is.na(ocean_depth) ~ 'Unknown',
        ocean_depth > local(b_max) ~ b_labs_plusgroup,
        TRUE ~ cut(ocean_depth, breaks, labels = b_labs, include.lowest = TRUE)
      ),
      ocean_depth_class = ifelse(
        is.na(ocean_depth_class),
        b_labs_plusgroup,
        ocean_depth_class
      )
    )
}

#' @param gear_group List mapping gear names to a vector of ``mfdb_gear_code`` values. Vectors can contain NA (i.e. missing gear codes will be assigned here) or ``pax_add_other()`` ("Other" value used for unassigned gear codes)
#' @return \subsection{pax_add_gear_group}{Query with an additional ``gear_name`` column, binning a ``mfdb_gear_code`` column}
#' @rdname pax_add_groupings
# Was: tidypax::add_gear_group
pax_add_gear_group <- function(
  tbl,
  gear_group = NULL,
  ignore_missing_col = FALSE
) {
  pcon <- dbplyr::remote_con(tbl)

  # NSE variables
  mfdb_gear_code <- NULL
  gear_name <- NULL
  coalesce <- NULL

  if (isTRUE(ignore_missing_col) && !("mfdb_gear_code" %in% colnames(tbl))) {
    # Column not present in this table, do nothing
    return(tbl)
  }

  if (is.null(gear_group)) {
    return(tbl |> dplyr::mutate(gear_name = 'all'))
  }

  # Pick off any default group
  default_group <- gear_group[sapply(gear_group, length) == 0]
  gear_group <- gear_group[sapply(gear_group, length) > 0]
  if (length(default_group) > 1) {
    stop(
      "More than one default group is not allowed, got: ",
      dput(default_group)
    )
  }

  gear_tbl <- gear_group |>
    purrr::map(~ tibble::tibble(mfdb_gear_code = .)) |>
    dplyr::bind_rows(.id = 'gear_name')

  out <- dplyr::left_join(tbl, pax_temptbl(pcon, gear_tbl))

  # Set any groups containing NA manually, as these won't join
  na_groups <- names(gear_group)[sapply(gear_group, function(x) any(is.na(x)))]
  if (length(na_groups) > 1) {
    stop("Only one gear_group can contain NA")
  } else if (length(na_groups) > 0) {
    out <- dplyr::mutate(
      out,
      gear_name = ifelse(is.na(mfdb_gear_code), local(na_groups), gear_name)
    )
  }

  # Set default for any still-unassigned groups
  if (length(default_group) > 0) {
    out <- dplyr::mutate(
      out,
      gear_name = coalesce(gear_name, local(names(default_group)[[1]]))
    )
  }

  return(out)
}

#' @param tgroup List mapping temporal groups(seasons) to a vector of ``month`` integers, i.e. ``1:12``. Vectors can contain NA for any columns without a month value. If not supplied, ``list(year = 1:12)`` is used.
#' @return \subsection{pax_add_temporal_grouping}{Query with an additional ``tgroup`` column, binning a ``month`` column}
#' @rdname pax_add_groupings
# Was: tidypax::add_temporal_grouping
pax_add_temporal_grouping <- function(
  tbl,
  tgroup = list(t1 = 1:6, t2 = 7:12),
  ignore_missing_col = FALSE
) {
  pcon <- dbplyr::remote_con(tbl)

  # NSE variables
  month <- NULL

  if (isTRUE(ignore_missing_col) && !("month" %in% colnames(tbl))) {
    # Column not present in this table, do nothing
    return(tbl)
  }

  if (is.null(tgroup)) {
    return(tbl |> dplyr::mutate(tgroup = 'year'))
  }

  tgroup_tbl <- tgroup |>
    purrr::map(~ tibble::tibble(month = .)) |>
    dplyr::bind_rows(.id = 'tgroup')

  out <- tbl |>
    dplyr::left_join(pax_temptbl(pcon, tgroup_tbl), by = "month") |>
    dplyr::mutate(tgroup = coalesce(tgroup, 'Other'))

  # Set any groups containing NA manually, as these won't join
  na_groups <- names(tgroup)[sapply(tgroup, function(x) any(is.na(x)))]
  if (length(na_groups) > 1) {
    stop("Only one tgroup can contain NA")
  } else if (length(na_groups) > 0) {
    out <- dplyr::mutate(
      out,
      tgroup = ifelse(is.na(month), local(na_groups), tgroup)
    )
  }

  return(out)
}

#' @param ygroup List mapping year groups to a vector of ``year`` integers, i.e. ``1:12``. Vectors can contain NA for any columns without a year value. If not supplied, there will be one ``ygroup`` per ``year``.
#' @return \subsection{pax_add_yearly_grouping}{Query with an additional ``ygroup`` column, binning a ``year`` column}
#' @rdname pax_add_groupings
# Was: tidypax::add_yearly_grouping
pax_add_yearly_grouping <- function(
  tbl,
  ygroup = NULL,
  ignore_missing_col = FALSE
) {
  pcon <- dbplyr::remote_con(tbl)

  # NSE variables
  year <- NULL

  if (isTRUE(ignore_missing_col) && !("year" %in% colnames(tbl))) {
    # Column not present in this table, do nothing
    return(tbl)
  }

  if (is.null(ygroup)) {
    return(tbl |> dplyr::mutate(ygroup = year))
  }

  ygroup_tbl <- ygroup |>
    purrr::map(~ tibble::tibble(year = .)) |>
    dplyr::bind_rows(.id = 'ygroup')

  out <- tbl |>
    dplyr::left_join(pax_temptbl(pcon, ygroup_tbl), by = 'year') |>
    dplyr::mutate(ygroup = coalesce(ygroup, year))

  # Set any groups containing NA manually, as these won't join
  na_groups <- names(ygroup)[sapply(ygroup, function(x) any(is.na(x)))]
  if (length(na_groups) > 1) {
    stop("Only one ygroup can contain NA")
  } else if (length(na_groups) > 0) {
    out <- dplyr::mutate(
      out,
      ygroup = ifelse(is.na(year), local(na_groups), ygroup)
    )
  }

  return(out)
}

#' @return \subsection{pax_add_other}{Placeholder to mark "other" group}
#' @rdname pax_add_groupings
pax_add_other <- function() {
  NULL
}
